version: "3.8"
networks:
  backend:
    driver: bridge
  view:
    driver: bridge
services:
  database:
    image: postgres:13.1-alpine
    container_name: devchat-database
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports: 
      - "5432:5432"
    networks:
      - backend
  server:
    build: ./backend
    container_name: devchat-backend
    volumes:
      - ./backend:/usr/server
    env_file:
      - .env
    ports: 
      - "3000:3000"
    depends_on:
      - database
    networks:
      - backend
      - view
  frontend:
    build: ./frontend
    container_name: devchat-frontend
    volumes:
      - ./frontend:/usr/server
    env_file:
      - .env
    ports: 
      - "3001:3001"
    depends_on:
      - server
    networks:
      - view