version: "3"

services:
  server:
    build: ./backend
    container_name: devchat-backend
    volumes:
      - ./backend:/usr/server
    environment:
      - PORT=3000
      - NODE_ENV=dev
    ports: 
      - "3000:3000"